apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  PRODUCTS_SERVICE_URL: "http://products-service:3003"
  ORDERS_SERVICE_URL: "http://orders-service:3004"
  CART_SERVICE_URL: "http://cart-service:3005"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  DB_HOST: "postgres"
  DB_PORT: "5432"
