apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/services/products-service
patches:
  - path: patch-replicas.yaml
images:
  - name: microservices/products-service
    newTag: latest
